version: "3.7"

services:

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]

  rag:
    image: tiangolo/uwsgi-nginx-flask:python3.11
    restart: unless-stopped
    environment:
      - TRANSFORMERS_CACHE=/app/models
      - OLLAMA_URL=http://ollama
      - OLLAMA_PORT=11434
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./venv/lib/python3.11/site-packages:/usr/local/lib/python3.11/site-packages
